// import { Inter, libreBaskerville } from "next/font/google";
import { libreBaskerville } from './utils/fonts'
import "./globals.css";
import { ContextProvider } from "./context/ContextProvider";
import Sidebar from './ui/Sidebar/Sidebar';
import StoreProvider from './redux/provider';
import Navbar from './ui/Navbar/Navbar';
import { ThemeProvider } from './utils/ThemeProvider';


export const metadata = {
  title: "optivacp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en" >
        <body className={`${libreBaskerville.variable} dark:bg-black`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <ContextProvider>
            <div className='w-full '>
              <div className='fixed  z-20 top-0 left-0'>
                <Sidebar/>
              </div>
              <div className='px-4 '>
                <div className='fixed z-10 w-full top-0 left-0 right-0 '>
                  <Navbar/>
                </div>
                {children}
              </div>
            </div>
          </ContextProvider>
        </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
