// import { Inter, libreBaskerville } from "next/font/google";
import { libreBaskerville } from './utils/fonts'

import "./globals.css";
import { ContextProvider } from "./context/ContextProvider";
import Sidebar from './ui/Sidebar/Sidebar';
import StoreProvider from './redux/provider';
import Navbar from './ui/Navbar/Navbar';
import { ThemeProvider } from './utils/ThemeProvider';
import LayoutContent from './utils/LayoutContent';
import { Toaster } from '@/components/ui/toaster';


export const metadata = {
  title: "optivacp",
  description: "optival capitals",
  icons:{
    icon:'/icon/optivac.png',
    shortcut:'/icon/optivac.png',
    apple:'/icon/optivac.png',
    other:[
      {
        reL:'icon',
        url:'/icon/optivac.png'
      }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${libreBaskerville.variable} dark:bg-black`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <ContextProvider>
            <div className='flex'>
                <LayoutContent>
                  {children}
                </LayoutContent>
                <Toaster />
            </div>
          </ContextProvider>
        </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}


// import React from 'react';
// import { libreBaskerville } from './utils/fonts';
// import "./globals.css";
// import { ContextProvider } from "./context/ContextProvider";
// import StoreProvider from './redux/provider';
// import { ThemeProvider } from './utils/ThemeProvider';
// import LayoutContent from './utils/LayoutContent';

// export const metadata = {
//   title: "optivacp",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <StoreProvider>
//       <html lang="en">
//         <body className={`${libreBaskerville.variable} dark:bg-black`} suppressHydrationWarning={true}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <ContextProvider>
//               <LayoutContent>
//                 {children}
//               </LayoutContent>
//             </ContextProvider>
//           </ThemeProvider>
//         </body>
//       </html>
//     </StoreProvider>
//   );
// }
